extends:
  - '@oacore/eslint-config-react'

parser: babel-eslint
env:
  browser: true
settings:
  import/resolver:
    node:
      paths: ['.']
      extensions: ['.js', '.jsx']


globals: {
  GA_TRACKING_CODE: true,
  BUILD_TARGET: true,
  SENTRY_DSN: true,
}
